/*
 * Copyright (c) 2014 iThings4U Gmbh
 * 
 * Author:
 *      Peter Dwersteg      
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace relayr_csharp_sdk
{
    public enum QualityOfService
    {
        AtLeastOnce,
        AtMostOnce,
        ExactlyOnce,
        GrantedFailure
    }

    public enum ApiCall
    {
        [Uri("users/validate?email=!")]
        [OperationType("GET")]
        UserCheckEmail,
        [Uri("oauth2/user-info")]
        [OperationType("GET")]
        UserGetInfo,
        [Uri("users/!")]
        [OperationType("PATCH")]
        UserUpdateDetails,
        [Uri("publishers")]
        [OperationType("GET")]
        PublishersReturnList,
        [Uri("publishers")]
        [OperationType("POST")]
        PublishersRegister,
        [Uri("publishers/!")]
        [OperationType("PATCH")]
        PublisherUpdateAttributes,
        [Uri("publishers/!")]
        [OperationType("DELETE")]
        PublisherDelete,
        [Uri("users/!/publishers")]
        [OperationType("GET")]
        PublishersListByUser,
        [Uri("apps")]
        [OperationType("GET")]
        ApplicationsListAll,
        [Uri("apps")]
        [OperationType("POST")]
        ApplicationsAddNew,
        [Uri("oauth2/app-info")]
        [OperationType("GET")]
        ApplicationsGetInfo,
        [Uri("oauth2/appdev-token/!")]
        [OperationType("GET")]
        ApplicationsReturnToken,
        [Uri("oauth2/appdev-token/!")]
        [OperationType("POST")]
        ApplicationsReplaceToken,
        [Uri("oauth2/appdev-token/!")]
        [OperationType("DELETE")]
        ApplicationDeleteToken,
        [Uri("apps/!")]
        [OperationType("GET")]
        ApplicationsRetrievePublisherApp,
        [Uri("apps/!")]
        [OperationType("PATCH")]
        ApplicationsUpdateAttributes,
        [Uri("apps/!")]
        [OperationType("DELETE")]
        ApplicationsDeleteApp,
        [Uri("users/!/apps/!")]
        [OperationType("POST")]
        ApplicationInstallAppUnderUser,
        [Uri("users/!/apps/!")]
        [OperationType("DELETE")]
        ApplicationUninstallAppUnderUser,
        [Uri("users/!/apps/!")]
        [OperationType("GET")]
        ApplicationInstalledAppInfo,
        [Uri("users/!/apps")]
        [OperationType("GET")]
        ApplicationListUserApps,
        [Uri("devices/!/apps")]
        [OperationType("GET")]
        ApplicationsListConnectedToDevice,
        [Uri("publishers/!/apps")]
        [OperationType("GET")]
        ApplicationsListByPublisher,
        [Uri("publishers/!/apps/extended")]
        [OperationType("GET")]
        ApplicationsListByPublisherExtended,
        [Uri("apps/!/devices/!")]
        [OperationType("POST")]
        ApplicationsConnectAppToDevice,
        [Uri("apps/!/devices/!")]
        [OperationType("DELETE")]
        ApplicationsDisconnectAppFromDevice,
        [Uri("devices")]
        [OperationType("POST")]
        DevicesRegisterNew,
        [Uri("users/!/devices?")]
        [OperationType("GET")]
        DevicesListUnderSpecificUser,
        [Uri("users/!/devices?meaning=!")]
        [OperationType("GET")]
        DevicesListUnderSpecificUserWithMeaning,
        [Uri("devices/!")]
        [OperationType("GET")]
        DeviceInformation,
        [Uri("devices/!")]
        [OperationType("PATCH")]
        DevicesUpdateAttributes,
        [Uri("devices/!")]
        [OperationType("DELETE")]
        DevicesDelete,
        [Uri("devices/!/apps/!")]
        [OperationType("POST")]
        DevicesConnectDeviceToApp,
        [Uri("devices/!/apps/!")]
        [OperationType("DELETE")]
        DevicesDisconnectDeviceFromApp,
        [Uri("/devices/public?")]
        [OperationType("GET")]
        DevicesListPublic,
        [Uri("/devices/public?meaning=!")]
        [OperationType("GET")]
        DevicesListPublicWithMeaning,
        [Uri("devices/!/subscription")]
        [OperationType("POST")]
        DevicesSubscribeUserToPublic,
        [Uri("users/!/devices/!/bookmarks")]
        [OperationType("POST")]
        DevicesBookmarkPublic,
        [Uri("users/!/devices/!/bookmarks")]
        [OperationType("DELETE")]
        DevicesDeleteBookmarkPublic,
        [Uri("users/!/devices/bookmarks")]
        [OperationType("GET")]
        DevicesListBookmarkedByUser,
        [Uri("device-models")]
        [OperationType("GET")]
        DevicesListOfModels,
        [Uri("device-models/!")]
        [OperationType("GET")]
        DevicesGetInfoAboutModel,
        [Uri("device-models/!/firmware")]
        [OperationType("GET")]
        DevicesGetFirmwareListForModel,
        [Uri("device-models/!/firmware/!")]
        [OperationType("GET")]
        DevicesGetFirmwareVersionRecord,
        [Uri("device-models/meanings")]
        [OperationType("GET")]
        DevicesListPossibleReadingTypes,
        [Uri("wunderbars/!")]
        [OperationType("DELETE")]
        WunderBarDelete,
        [Uri("devices/!/firmware")]
        [OperationType("GET")]
        DeviceConfigurationInformation,
        [Uri("devices/!/configuration")]
        [OperationType("POST")]
        DeviceModifyConfiguration,
        [Uri("devices/!/cmd")]
        [OperationType("POST")]
        DeviceIssueCommand,
        [Uri("devices/!/cmd/!")]
        [OperationType("POST")]
        DeviceIssueCommandWithSuffix,
        [Uri("transmitters")]
        [OperationType("POST")]
        TransmittersRegister,
        [Uri("users/!/transmitters")]
        [OperationType("GET")]
        TransmittersListByUser,
        [Uri("transmitters/!")]
        [OperationType("GET")]
        TransmittersGetSpecificInformation,
        [Uri("transmitters/!")]
        [OperationType("PATCH")]
        TransmittersUpdate,
        [Uri("transmitters/!")]
        [OperationType("DELETE")]
        TransmittersDelete,
        [Uri("transmitter/!/device/!")]
        [OperationType("POST")]
        TransmittersConnectToDevice,
        [Uri("transmitter/!/device/!")]
        [OperationType("DELETE")]
        TransmittersDisconnectFromDevice,
        [Uri("transmitters/!/devices")]
        [OperationType("GET")]
        TransmittersListConnectedDevices,
        [Uri("channels")]
        [OperationType("POST")]
        CreateChannel
    }

}
